services:
  db:
    image: sqlite3
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  bot:
    build: .
    container_name: dtb_bot
    command: python manage.py bot
    env_file:
      - ./.env
    depends_on:
      - web